vim.keymap.set("i", "jj", "<ESC>", nil)
vim.keymap.set("n", "<C-d>", "<C-d>zz", nil)
vim.keymap.set("n", "<C-u>", "<C-u>zz", nil)
vim.keymap.set("n", "n", "nzz", nil)
vim.keymap.set("n", "N", "Nzz", nil)
